POST http://localhost:3004/api/blogs
Content-Type: application/json

{
    "title": "Home decor blog",
    "author": "Mary Poppins",
    "url": "http://blog.com",
    "likes": 10,
    "user": "5f91ca1c0b4c5f5ad4707ae3"
}